package ua.kpi.eec.vml.model.entity;

// Generated 23-Sep-2014 17:21:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Account generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "account", schema = "public", uniqueConstraints = {
		@UniqueConstraint(columnNames = "moodle_id"),
		@UniqueConstraint(columnNames = "email") })
public class Account implements java.io.Serializable {

	private int id;
	private int moodleId;
	private String email;
	private String fullName;
	private String role;
	private Set taskLogs = new HashSet(0);
	private Set courseRoles = new HashSet(0);

	public Account() {
	}

	public Account(int id, int moodleId, String email, String fullName,
			String role) {
		this.id = id;
		this.moodleId = moodleId;
		this.email = email;
		this.fullName = fullName;
		this.role = role;
	}

	public Account(int id, int moodleId, String email, String fullName,
			String role, Set taskLogs, Set courseRoles) {
		this.id = id;
		this.moodleId = moodleId;
		this.email = email;
		this.fullName = fullName;
		this.role = role;
		this.taskLogs = taskLogs;
		this.courseRoles = courseRoles;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "moodle_id", unique = true, nullable = false)
	public int getMoodleId() {
		return this.moodleId;
	}

	public void setMoodleId(int moodleId) {
		this.moodleId = moodleId;
	}

	@Column(name = "email", unique = true, nullable = false, length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "full_name", nullable = false, length = 200)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "role", nullable = false, length = 200)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set getTaskLogs() {
		return this.taskLogs;
	}

	public void setTaskLogs(Set taskLogs) {
		this.taskLogs = taskLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set getCourseRoles() {
		return this.courseRoles;
	}

	public void setCourseRoles(Set courseRoles) {
		this.courseRoles = courseRoles;
	}

}
