package ua.kpi.eec.vml.model.entity;

// Generated 23-Sep-2014 17:21:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course", schema = "public")
public class Course implements java.io.Serializable {

	private static final long serialVersionUID = -4824245796884766335L;

	private int id;
	private I18n i18n;
	private int nameI18nId;
	private Set tasks = new HashSet(0);
	private Set courseRoles = new HashSet(0);

	public Course() {
	}

	public Course(int id, I18n i18n, int nameI18nId) {
		this.id = id;
		this.i18n = i18n;
		this.nameI18nId = nameI18nId;
	}

	public Course(int id, I18n i18n, int nameI18nId, Set tasks, Set courseRoles) {
		this.id = id;
		this.i18n = i18n;
		this.nameI18nId = nameI18nId;
		this.tasks = tasks;
		this.courseRoles = courseRoles;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "description_i18n_id", nullable = false)
	public I18n getI18n() {
		return this.i18n;
	}

	public void setI18n(I18n i18n) {
		this.i18n = i18n;
	}

	@Column(name = "name_i18n_id", nullable = false)
	public int getNameI18nId() {
		return this.nameI18nId;
	}

	public void setNameI18nId(int nameI18nId) {
		this.nameI18nId = nameI18nId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set getTasks() {
		return this.tasks;
	}

	public void setTasks(Set tasks) {
		this.tasks = tasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set getCourseRoles() {
		return this.courseRoles;
	}

	public void setCourseRoles(Set courseRoles) {
		this.courseRoles = courseRoles;
	}

}
