package ua.kpi.eec.vml.model.entity;

// Generated 23-Sep-2014 17:21:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * I18n generated by hbm2java
 */
@Entity
@Table(name = "i18n", schema = "public")
public class I18n implements java.io.Serializable {

	private int id;
	private Set i18nValues = new HashSet(0);
	private Set modulesForPageContentI18nId = new HashSet(0);
	private Set pagesForNameI18nId = new HashSet(0);
	private Set pagesForContentI18nId = new HashSet(0);
	private Set modulesForNameI18nId = new HashSet(0);
	private Set tasksForDefinitionI18nId = new HashSet(0);
	private Set rooms = new HashSet(0);
	private Set modulesForDescriptionI18nId = new HashSet(0);
	private Set courses = new HashSet(0);
	private Set tasksForContentI18nId = new HashSet(0);

	public I18n() {
	}

	public I18n(int id) {
		this.id = id;
	}

	public I18n(int id, Set i18nValues, Set modulesForPageContentI18nId,
			Set pagesForNameI18nId, Set pagesForContentI18nId,
			Set modulesForNameI18nId, Set tasksForDefinitionI18nId, Set rooms,
			Set modulesForDescriptionI18nId, Set courses,
			Set tasksForContentI18nId) {
		this.id = id;
		this.i18nValues = i18nValues;
		this.modulesForPageContentI18nId = modulesForPageContentI18nId;
		this.pagesForNameI18nId = pagesForNameI18nId;
		this.pagesForContentI18nId = pagesForContentI18nId;
		this.modulesForNameI18nId = modulesForNameI18nId;
		this.tasksForDefinitionI18nId = tasksForDefinitionI18nId;
		this.rooms = rooms;
		this.modulesForDescriptionI18nId = modulesForDescriptionI18nId;
		this.courses = courses;
		this.tasksForContentI18nId = tasksForContentI18nId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "i18n")
	public Set getI18nValues() {
		return this.i18nValues;
	}

	public void setI18nValues(Set i18nValues) {
		this.i18nValues = i18nValues;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "i18nByPageContentI18nId")
	public Set getModulesForPageContentI18nId() {
		return this.modulesForPageContentI18nId;
	}

	public void setModulesForPageContentI18nId(Set modulesForPageContentI18nId) {
		this.modulesForPageContentI18nId = modulesForPageContentI18nId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "i18nByNameI18nId")
	public Set getPagesForNameI18nId() {
		return this.pagesForNameI18nId;
	}

	public void setPagesForNameI18nId(Set pagesForNameI18nId) {
		this.pagesForNameI18nId = pagesForNameI18nId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "i18nByContentI18nId")
	public Set getPagesForContentI18nId() {
		return this.pagesForContentI18nId;
	}

	public void setPagesForContentI18nId(Set pagesForContentI18nId) {
		this.pagesForContentI18nId = pagesForContentI18nId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "i18nByNameI18nId")
	public Set getModulesForNameI18nId() {
		return this.modulesForNameI18nId;
	}

	public void setModulesForNameI18nId(Set modulesForNameI18nId) {
		this.modulesForNameI18nId = modulesForNameI18nId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "i18nByDefinitionI18nId")
	public Set getTasksForDefinitionI18nId() {
		return this.tasksForDefinitionI18nId;
	}

	public void setTasksForDefinitionI18nId(Set tasksForDefinitionI18nId) {
		this.tasksForDefinitionI18nId = tasksForDefinitionI18nId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "i18n")
	public Set getRooms() {
		return this.rooms;
	}

	public void setRooms(Set rooms) {
		this.rooms = rooms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "i18nByDescriptionI18nId")
	public Set getModulesForDescriptionI18nId() {
		return this.modulesForDescriptionI18nId;
	}

	public void setModulesForDescriptionI18nId(Set modulesForDescriptionI18nId) {
		this.modulesForDescriptionI18nId = modulesForDescriptionI18nId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "i18n")
	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "i18nByContentI18nId")
	public Set getTasksForContentI18nId() {
		return this.tasksForContentI18nId;
	}

	public void setTasksForContentI18nId(Set tasksForContentI18nId) {
		this.tasksForContentI18nId = tasksForContentI18nId;
	}

}
